### ISSUE TITLE
"closeEsc: false" Don't work on Firefox

### ISSUE THREAD

**Issue by osirismqz** [buckwilson/Lightbox_me#1]
If you turn closeEsc to false works on every browser but Firefox.

Tested on Firefox 3.6

**Comment by buckwilson** [comment]
Working for me on 3.6.3–  is there something intercepting the keydown event on your page?

tested here: http://buckwilson.me/lightboxme/ (the try me link midway through)

**Comment by osirismqz** [comment]
Sorry, I just noticed my mistake.

I meaned "closeEsc: false"

**Comment by evoactivity** [comment]
This didn't work for me either, I had to change the keypress event bound to the window to a keyup and it is fine now.

**Comment by buckwilson** [comment]
Strange. I'll look into it as soon as I can (or feel free to make changes to the code directly)

**Comment by ryangiglio** [comment]
I believe I've fixed this bug in my fork.

**Comment by buckwilson** [comment]
Yep it's fixed and rolled into master. Thanks, Ryan!
