### ISSUE TITLE
removeModal is called before it's bound to overlay[0]

### ISSUE THREAD

**Issue by choxi** [buckwilson/Lightbox_me#16]
I was unit testing my javascripts and got an error saying that "overlay[0].removeModal is not a function" and I traced it down to this code block:

```
if ($overlay.length > 0) {
    $overlay[0].removeModal = removeModal; // I added this binding
    $overlay[0].removeModal(); // if the overlay exists, then a modal probably exists. Ditch it!
 } else {
   $overlay =  $('<div class="' + opts.classPrefix + '_overlay" style="display:none;"/>'); // otherwise just create an all new overlay. 
 } 
```

It looks like you bind removeModal to overlay[0] somewhere lower in the code so that it raises an exception if you call it before. I'm not sure if that's actually the issue or if I'm doing something wrong in my tests, I fixed it by adding the binding earlier but if I'm mistaken I'd appreciate anyone who could point out what I'm misunderstanding. Thanks.

**Comment by milholen** [comment]
Can you mention where you moved the binding code to? I'm having an issue (see Open Issues for this project) that might be affected by this.

**Comment by choxi** [comment]
I added an extra binding when the overlay already exists: choxi@394fd0990

**Comment by buckwilson** [comment]
Hi choxi, since then this code block has been removed completely. I need to better handle the case where an overlay already exists, but I'm not sure the best way to go about this yet.
