### ISSUE TITLE
lightboxed element not in foreground

### ISSUE THREAD

**Issue by fenfe1** [buckwilson/Lightbox_me#2]
Hi,

When I try to use the plugin it creates the overall and outputs the correct element to lightbox but its hidden behind the main page.

The lightboxed element has the highest z-index (1002) so I don't know why its not the foremost element.

If you want to see an example see here: http://help.felixfennell.co.uk/sample.php

Otherwise a fantastic plugin, thanks for sharing!

Felix

**Comment by Zielun** [comment]
Try to set flash object wmode param to opaque.

**Comment by fenfe1** [comment]
Thanks for the reply, 

I didn't know about that parameter, problem solved :)

Felix

**Comment by buckwilson** [comment]
People helping people! AWESOME!
