### ISSUE TITLE
closeClick option not working?

### ISSUE THREAD

**Issue by damonmannion** [buckwilson/Lightbox_me#24]
turning off closeClick doesn't seem to be working

line 97 reads:
    $overlay.click(function(e) { closeLightbox(); e.preventDefault; });

should this be:
    if( opts.closeClick )
      $overlay.click(function(e) { closeLightbox(); e.preventDefault; });

**Comment by stephens2424** [comment]
I already listed this as issue #21 and have submitted a pull request with this fix, but if you want, I have it done here: https://github.com/stephens2424/Lightbox_me

**Comment by buckwilson** [comment]
Thanks for the help man!
