### ISSUE TITLE
Opening External Files

### ISSUE THREAD

**Issue by influxweb** [buckwilson/Lightbox_me#25]
Just wondering if anyone has had any success with using Lightbox_me to open an external page (ajax, iframe, etc...)? I love using this plugin for images and on-page content, but I have run into the need to open external elements as well and was hoping to not have to switch to a more complex plugin like FancyBox or ColorBox.

Thank you,
Matt

**Comment by buckwilson** [comment]
Howdy Matt!

I haven't tried it myself, but I believe others have been able to use lb_me for exactly what you need it for. Since lb_me just modals what you give it, you should be able to give it an iFrame or HTML generated by ajax return without issue. The element doesn't have to be in the DOM to give it to lb_me, even newly created DOM elements via jQuery will work just fine.

**Comment by influxweb** [comment]
Hi Buck,

Thank you for the information. I'm not too familiar with adding functions like that, but I guess there's no better time to experiment and learn than now.

**Comment by buckwilson** [comment]
If you have an iframe in the DOM, just do $("iframeselector").lightbox_me();

If your AJAX returns HTML straight away you can do $(data).lightbox_me() from within your $.ajax call. Let me know if I can help out!

**Comment by influxweb** [comment]
Hi Buck,

Thank you again for the information and direction. I have a hidden DIV on the page with an ID of "sizeChart" and I was able to accomplish what I was after by using the following code:

``` javascript
$('#open-size-chart').click(function(e){
    var pageSrc=$(this).attr('href');
    $.get(pageSrc, function(data){
        var pageData=data + '<img src="../images/icons/error.png" alt="Close" title="Close" class="close" />';
        $('#sizeChart').html(pageData).lightbox_me({
            closeSelector:'.close',
            centered:true
        });
    });
    e.preventDefault();
});
```

**Comment by scottkf** [comment]
Using $(data).lightbox_me() with valid html from an ajax/get request yields `Uncaught TypeError: Cannot read property 'width' of undefined` errors repeatedly. 

Changing showOverlay to false halts the errors, shows the content, but without an overlay :(

Any insight into this?

**Comment by scottkf** [comment]
To make this more generic, this is what I came up with:

```
ajax_lightbox = function(selector, wrapper) {
  if (wrapper == null) {
    wrapper = 'lightbox_me';
  }
 $(selector).click(function(e) {
    var lightbox;
    lightbox = '<div id="' + wrapper + '"></div>';
    if ($('#' + wrapper).length === 0) {
      $('body').append(lightbox);
    }
    $.get($(selector).attr('href'), function(data) {
      var html;
      html = data + '<a id="close_lightbox_me" class="close" href="#">close</a>';
      $('#close_lightbox_me').click(function(ev) {
        ev.preventDefault();
        ev.trigger('close');
      });
      $('#' + wrapper).html(html).lightbox_me();
    });
    e.preventDefault();
  });
};

    // Use with
ajax_lightbox("a[rel='ajax']");
```

There are better ways to write this and integrate this into your library, but it's just a temporary solution

**Comment by influxweb** [comment]
Hi Scott,

Thank you for the more universal solution. To reply to your first question, I wasn't able to get $(data).lightbox_me() to function for me either, I just chalked it up to how the content is being rendered on the page.

**Comment by buckwilson** [comment]
I'll look into this case and make sure it doesn't error out. If nothing else, the plugin should handle injecting the markup into the DOM so that it can pull a width properly.

**Comment by KarSho** [comment]
Uncaught TypeError: Object [object Object] has no method 'lightbox_me'
