### ISSUE TITLE
Positioning

### ISSUE THREAD

**Issue by saschaw** [buckwilson/Lightbox_me#31]
Hi there,

is there any way to position the box? I dont´t need it centered but about 150px more above and 50px more right.

Thanks in advance

**Comment by buckwilson** [comment]
There's no way to position it relative to its centered position, but you can position it manually relative to the document.

set centered: false; (this is default, I believe) and set the modalCSS parameter to whatever you like, such as:

{top: '150px', right: '150px'}

**Comment by saschaw** [comment]
Thanks, that work´s, but it´s nit the best solution. Another way that I´ve found is to put the content into another div width 100% of height and 265px of width, then force the content to float right and it´s positioned the way i want.
But then I have the problem, that I can´t close the box above and under the "real" content of the box.
How can I trigger the close click for that?

**Comment by buckwilson** [comment]
Honestly if you're manually positioning the div then lightbox_me probably isn't what you need, as lightbox_me's code is mostly dedicated to figuring out the position for you.

**Comment by saschaw** [comment]
Maybe you´re right, I´m thinking of using another one. But you did really a good job, it´s working fine (except the positioning )_;  )

**Comment by buckwilson** [comment]
Depending on your jQuery & CSS knowledge you may not need a plugin at all. Just set your modal to position: absolute, put it as a direct descendant of <body> and position it manually. 

I may make a modification to lightbox_me to allow you to completely manually position the modal in the future. Thanks for the feedback.
