### ISSUE TITLE
lightbox dynamic

### ISSUE THREAD

**Issue by gabs77** [buckwilson/Lightbox_me#5]
How do you use to open ovelay only one image and not all with the same class ? I don't want specify a id because it must be dynamic.

Example:
&lt;script&gt;
$(function() {$("img.thumbs").click(function() { $("img.full").lightbox_me({centered: true }); return false; }); });
&lt;/script&gt;

&lt;img class="thumb" src="thumbs_123465.jpg"/&gt;
&lt;img class="full" style="display:none" src="full_123465.jpg"/&gt;
&lt;img class="thumb" src="thumbs_456789.jpg"/&gt;
&lt;img class="full" style="display:none" src="456789.jpg"/&gt;

**Comment by buckwilson** [comment]
Use whatever jQuery selector suits your fancy. It seems in this case you'd want something like $(this).next('img.full').lightbox_me...
which will find the next img element class full relative to the image clicked on and lightbox it.
