### ISSUE TITLE
Access Denied Error in IE9

### ISSUE THREAD

**Issue by TBenedyk** [buckwilson/Lightbox_me#53]
My lightbox works fine on all browsers except IE. I have tested in IE9 and I get 

SCRIPT5: Access is denied. jquery.js?body=1, line 5928 character 2

I am using jQuery 1.8.0, and my code is as follows.

jQuery(function(){
  $('.openLogin, #openLogin').click(function(e) {
    e.preventDefault();
    $('.loginLightboxForm').show();
    $('.lightBoxWhite').lightbox_me({
        centered: false,
        modalCSS:  {top: '80px'},
        overlayCSS: {background: '#000000', opacity: .6},
        onClose: function() {
            $('.loginLightboxForm').hide()
            }
        });
  });
});

**Comment by dbashyal** [comment]
I am getting same issue, was there solution for this? if not why it's closed? Any help would be appreciated.

After debug i found where the code is failing:

```
$iframe = $('<iframe id="foo" style="z-index: ' + (opts.zIndex + 1) + ';border: none; margin: 0; padding: 0; position: absolute; width: 100%; height: 100%; top: 0; left: 0; filter: mask();"/>'),
```
