### ISSUE TITLE
Broken in IE7

### ISSUE THREAD

**Issue by jamosonic** [buckwilson/Lightbox_me#6]
Lightbox fails to activate in IE7

**Comment by jamosonic** [comment]
Buck, it seems whatever fixes are being applied to IE6 need to be applied to IE7 as well. Changing line 39 to the following fixes it:

ie6 = ($.browser.msie && $.browser.version < 8);

**Comment by buckwilson** [comment]
Hm, strange– I'll look into it, but that does some unnecessary things to the dom element in IE7 (creates an iframe shim and sets expressions to fake position: fixed); I'll see if I can replicate the issue and track it down.
