### ISSUE TITLE
incomplete clean up events 

### ISSUE THREAD

**Issue by Cinetryx** [buckwilson/Lightbox_me#64]
You need to add in closeLightbox method an unbind to close trigger event

$self.unbind('close', closeLightbox);

Because after 2 call of 'lightboxme' you have trouble with to much call of close method

**Comment by pgilad** [comment]
absolutely right.. need to add the function you wrote in:
`function closeLightbox()` and also unbind the reposition event.

**Comment by buckwilson** [comment]
Fixed in latest. There were a couple of other event binding issues as well that were cleaned up. Thanks!
