### ISSUE TITLE
flot graph removed from page after lightbox_me close

### ISSUE THREAD

**Issue by romainecarter** [buckwilson/Lightbox_me#72]
I am light boxing some flot graphs with lightbox_me, it works fine for the initial load of the graphs however when i close the light box the original graph is destroyed. How do I resolve that issue.

**Comment by buckwilson** [comment]
Not sure honestly – lbme will move the element to be a direct child of body, but will not destroy the element unless destroyOnClose is set to true. Are you sure the element hasn't just moved?

**Comment by romainecarter** [comment]
Did some poking around and it was just set to display:none. Any plans to implement functionality to return the canvas to its original position and size?

**Comment by buckwilson** [comment]
I seem to remember a putBack option existing but not sure if that was a branch ever pushed. I'm honestly not sure of the most reliable way to do this, but you can store the closest parent when you trigger lightbox_me and do $parent.append($ele) onClose (where $ele is the element being lightboxed), but that only works if the element is the only or the last element of its parent.

**Comment by romainecarter** [comment]
I will try that thanks.
