### ISSUE TITLE
closeClick

### ISSUE THREAD

**Issue by tutsmarket** [buckwilson/Lightbox_me#8]
closeClick: false doesn't seem to be working for some reason - has no affect, when I click on the overlay the lightboxed content still closes. Any thoughts?

**Comment by ghost** [comment]
Hi!
I guess it is needed an if validation with closeClick value in this code:

$self.find(opts.closeSelector).add($overlay).click(function() { 
closeLightbox(); return false; 
});

change to:

$self.find(opts.closeSelector).add($overlay).click(function() { 
if(opts.closeClick){
closeLightbox(); return false; 
}
});

**Comment by patrickdevivo** [comment]
thank you! I'll check it out

**Comment by buckwilson** [comment]
Newest version of lb_me has this fix in place. Thanks for the help, leokorma!
