### ISSUE TITLE
closeSelector not working in firefox 3.66 and chrome 6.0.458.1

### ISSUE THREAD

**Issue by masdude** [buckwilson/Lightbox_me#9]
By defualt closeSelector is set to '.close' and closeClick is set to true, but since I change closeClick to false, then closeSelector is not working.

**Comment by masdude** [comment]
bugfixed:
change line92 to:

if(opts.closeClick){$self.find(opts.closeSelector).add($overlay).click(function(){console.log('click'); removeModal(true); return false;})} else{$self.find(opts.closeSelector).click(function() { console.log('click'); removeModal(true); return false; });}

**Comment by buckwilson** [comment]
Sorry this was an issue with a merge. I'll get the fix checked in soon.
